# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-07-24 23:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='income',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
