# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-03 05:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_userprofile_income'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountModule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name_plural': 'AccountModules',
                'verbose_name': 'AccountModule',
            },
        ),
        migrations.CreateModel(
            name='BasicAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userProfile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.UserProfile')),
            ],
            options={
                'verbose_name_plural': 'BasicAccounts',
                'verbose_name': 'BasicAccount',
            },
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('moduleName', models.CharField(max_length=50)),
                ('account', models.CharField(max_length=50)),
                ('isAddOn', models.BooleanField()),
            ],
            options={
                'verbose_name_plural': 'Module',
                'verbose_name': 'Module',
            },
        ),
        migrations.AddField(
            model_name='accountmodule',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.BasicAccount'),
        ),
        migrations.AddField(
            model_name='accountmodule',
            name='module',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.Module'),
        ),
    ]
