# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-08-07 02:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20160805_0507'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountmodule',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='account_modules', to='account.BasicAccount'),
        ),
        migrations.AlterField(
            model_name='accountmodule',
            name='module',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modules', to='account.Module'),
        ),
        migrations.AlterField(
            model_name='basicaccount',
            name='userProfile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vest_account', to='account.UserProfile'),
        ),
    ]
