# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-08-07 05:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_auto_20160807_0209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basicaccount',
            name='userProfile',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='vest_account', to='account.UserProfile'),
        ),
    ]
