# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-08-07 21:49
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_auto_20160807_0544'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='accountmodule',
            options={'ordering': ('createdAt',), 'verbose_name': 'AccountModule', 'verbose_name_plural': 'AccountModules'},
        ),
        migrations.AddField(
            model_name='accountmodule',
            name='createdAt',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2016, 8, 7, 21, 49, 10, 173580, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='module',
            name='category',
            field=models.CharField(default=datetime.datetime(2016, 8, 7, 21, 49, 13, 41765, tzinfo=utc), max_length=20),
            preserve_default=False,
        ),
    ]
