# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-08-08 00:20
from __future__ import unicode_literals

from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_auto_20160807_2149'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='chartFormat',
            field=jsonfield.fields.JSONField(default={}),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='module',
            name='chartType',
            field=models.CharField(default='asdf', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='module',
            name='endpoint',
            field=models.CharField(default='test', max_length=20),
            preserve_default=False,
        ),
    ]
