# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-08-08 00:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_auto_20160808_0020'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='email',
        ),
        migrations.AddField(
            model_name='basicaccount',
            name='linkedAccount',
            field=models.BooleanField(default=False),
        ),
    ]
