# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-08-19 14:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_auto_20160808_0028'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='moduleID',
            field=models.CharField(default='test', max_length=50),
            preserve_default=False,
        ),
    ]
