# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-06 19:35
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('createdAt', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('acceptedEmails', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Referal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('createdAt', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('accepted', models.BooleanField(default=False)),
                ('refree', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='landing.Email')),
            ],
        ),
    ]
