# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-22 20:37
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='holding',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cusip', models.CharField(max_length=9)),
                ('holdingType', models.CharField(max_length=20)),
                ('price', models.PositiveIntegerField()),
                ('priceCurrency', models.CharField(max_length=3)),
                ('quantity', models.PositiveIntegerField()),
                ('symbol', models.CharField(max_length=5)),
                ('allocation', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Ticker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=5)),
                ('lastUpdated', models.DateTimeField()),
                ('histValues', django.contrib.postgres.fields.jsonb.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='UserData',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='account.UserProfile')),
            ],
        ),
        migrations.AddField(
            model_name='holding',
            name='portfolio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.UserData'),
        ),
    ]
