# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-31 20:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='holding',
            name='contractQuanitty',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='holding',
            name='couponRate',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='holding',
            name='currencyType',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='holding',
            name='cusipNumber',
            field=models.CharField(blank=True, max_length=9, null=True),
        ),
        migrations.AlterField(
            model_name='holding',
            name='description',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='holding',
            name='exercisedQuantity',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='holding',
            name='expirationDate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='holding',
            name='grantDate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='holding',
            name='holdingType',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='holding',
            name='interestRate',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='holding',
            name='maturityDate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='holding',
            name='optionType',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='holding',
            name='providerAccountID',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='holding',
            name='quantity',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='holding',
            name='symbol',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='holding',
            name='term',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='holding',
            name='unvestedQuantity',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='holding',
            name='vestedQuantity',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='holding',
            name='vestedSharesExercisable',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='holding',
            name='vestingDate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='investmentoption',
            name='cusipNumber',
            field=models.CharField(blank=True, max_length=9, null=True),
        ),
        migrations.AlterField(
            model_name='investmentoption',
            name='description',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='investmentoption',
            name='fiveYearReturn',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='investmentoption',
            name='grossExpenseRatio',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='investmentoption',
            name='holdingType',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='investmentoption',
            name='inceptionDate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='investmentoption',
            name='inceptionToDateReturn',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='investmentoption',
            name='isin',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='investmentoption',
            name='netExpenseRatio',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='investmentoption',
            name='oneMonthReturn',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='investmentoption',
            name='oneYearReturn',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='investmentoption',
            name='sedol',
            field=models.CharField(blank=True, max_length=7, null=True),
        ),
        migrations.AlterField(
            model_name='investmentoption',
            name='symbol',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='investmentoption',
            name='tenYearReturn',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='investmentoption',
            name='threeMonthReturn',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='investmentoption',
            name='yearToDateReturn',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='investmentplan',
            name='name',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='investmentplan',
            name='number',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='investmentplan',
            name='provider',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='refreshinfo',
            name='actionRequested',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='refreshinfo',
            name='additionalStatus',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='refreshinfo',
            name='message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='refreshinfo',
            name='status',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='refreshinfo',
            name='statusMessage',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='rewardbalance',
            name='balanceToLevel',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='rewardbalance',
            name='balanceToReward',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='rewardbalance',
            name='balanceType',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='rewardbalance',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='rewardbalance',
            name='units',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='yodleeaccount',
            name='accountName',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='yodleeaccount',
            name='accountNumber',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='yodleeaccount',
            name='accountType',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='yodleeaccount',
            name='apr',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='yodleeaccount',
            name='classification',
            field=models.CharField(blank=True, max_length=14, null=True),
        ),
        migrations.AlterField(
            model_name='yodleeaccount',
            name='currentLevel',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='yodleeaccount',
            name='dueDate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='yodleeaccount',
            name='enrollmentDate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='yodleeaccount',
            name='expirationDate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='yodleeaccount',
            name='homeInsuranceType',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='yodleeaccount',
            name='interestRate',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='yodleeaccount',
            name='lastEmployeeContributionDate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='yodleeaccount',
            name='lastPaymentDate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='yodleeaccount',
            name='lastUpdated',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='yodleeaccount',
            name='lifeInsuranceType',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='yodleeaccount',
            name='maturityDate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='yodleeaccount',
            name='nextLevel',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='yodleeaccount',
            name='nickname',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='yodleeaccount',
            name='policyStatus',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='yodleeaccount',
            name='premiumPaymentTerm',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='yodleeaccount',
            name='primaryRewardUnit',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='yodleeaccount',
            name='providerAccountId',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='yodleeaccount',
            name='providerId',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='yodleeaccount',
            name='providerName',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='yodleeaccount',
            name='status',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='yodleeaccount',
            name='term',
            field=models.TextField(blank=True, null=True),
        ),
    ]
