# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-10-09 18:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_quovouser_currenthistoricalindex'),
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserReturns',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('oneYearReturns', models.FloatField()),
                ('twoYearReturns', models.FloatField()),
                ('threeYearReturns', models.FloatField()),
                ('quovoUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userReturns', to='dashboard.QuovoUser')),
            ],
            options={
                'verbose_name': 'UserReturn',
                'verbose_name_plural': 'UserReturns',
            },
        ),
        migrations.AddField(
            model_name='userhistoricalholding',
            name='portfolioIndex',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
