# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-31 21:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0002_auto_20160731_2002'),
    ]

    operations = [
        migrations.AddField(
            model_name='yodleeaccount',
            name='annuityBalance',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='data.annuityBalance'),
        ),
    ]
