# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-22 21:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0002_auto_20160722_2112'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userdata',
            options={'verbose_name': 'UserData', 'verbose_name_plural': 'UserData'},
        ),
    ]
