# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-11-05 20:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0002_auto_20161009_1838'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='holding',
            name='ric',
        ),
        migrations.AddField(
            model_name='holding',
            name='isNAVValued',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='holding',
            name='secname',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='holdingexpenseratio',
            name='holding',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenseRatios', to='data.Holding'),
        ),
        migrations.AlterField(
            model_name='holdingprice',
            name='holding',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='holdingPrices', to='data.Holding'),
        ),
        migrations.AlterUniqueTogether(
            name='holdingprice',
            unique_together=set([('holding', 'closingDate')]),
        ),
    ]
