# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-22 22:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0003_auto_20160722_2136'),
    ]

    operations = [
        migrations.CreateModel(
            name='stock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=5)),
                ('lastUpdated', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='stockPrice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('price', models.DecimalField(decimal_places=6, max_digits=11)),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.stock')),
            ],
        ),
        migrations.DeleteModel(
            name='Ticker',
        ),
    ]
