# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-31 21:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0003_yodleeaccount_annuitybalance'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='_401kloan',
            new_name='a401kLoan',
        ),
    ]
