# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-01 00:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0004_auto_20160731_2155'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='yodleeaccount',
            name='annuityBalance',
        ),
    ]
