# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-11-05 20:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0004_auto_20161105_2017'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='holding',
            name='isNAVValued',
        ),
        migrations.AlterField(
            model_name='holding',
            name='secname',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
