# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-22 22:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0005_auto_20160722_2223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='lastUpdated',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='stockprice',
            name='date',
            field=models.DateField(),
        ),
    ]
