# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-01 00:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0006_auto_20160801_0052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='yodleeaccount',
            name='userData',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='yodleeAccount', to='data.UserData'),
        ),
    ]
