# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-01 19:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0007_auto_20160801_0056'),
    ]

    operations = [
        migrations.RenameField(
            model_name='holding',
            old_name='accountId',
            new_name='accountID',
        ),
        migrations.RenameField(
            model_name='holding',
            old_name='contractQuanitty',
            new_name='contractQuantity',
        ),
        migrations.RenameField(
            model_name='investmentoption',
            old_name='optionId',
            new_name='optionID',
        ),
        migrations.RenameField(
            model_name='investmentplan',
            old_name='planId',
            new_name='planID',
        ),
        migrations.RenameField(
            model_name='yodleeaccount',
            old_name='providerAccountId',
            new_name='providerAccountID',
        ),
        migrations.RenameField(
            model_name='yodleeaccount',
            old_name='providerId',
            new_name='providerID',
        ),
    ]
