# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-11-13 00:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0008_auto_20161108_0159'),
    ]

    operations = [
        migrations.AddField(
            model_name='holding',
            name='shouldIgnore',
            field=models.BooleanField(default=False),
        ),
    ]
