# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-25 14:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_userprofile_income'),
        ('data', '0008_auto_20160723_0027'),
    ]

    operations = [
        migrations.RenameField(
            model_name='holding',
            old_name='portfolio',
            new_name='userData',
        ),
        migrations.RemoveField(
            model_name='userdata',
            name='user',
        ),
        migrations.AddField(
            model_name='userdata',
            name='userProfile',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='data', to='account.UserProfile'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='stockprice',
            name='stock',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.Stock'),
        ),
    ]
