# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-11-20 00:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0009_holding_shouldignore'),
    ]

    operations = [
        migrations.CreateModel(
            name='HoldingBondBreakdown',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=30)),
                ('percentage', models.FloatField()),
                ('createdAt', models.DateField(auto_now_add=True)),
                ('updateIndex', models.PositiveIntegerField()),
                ('holding', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bondBreakdowns', to='data.Holding')),
            ],
            options={
                'verbose_name': 'HoldingBondBreakdown',
                'verbose_name_plural': 'HoldingBondBreakdowns',
            },
        ),
        migrations.CreateModel(
            name='HoldingEquityBreakdown',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=30)),
                ('percentage', models.FloatField()),
                ('createdAt', models.DateField(auto_now_add=True)),
                ('updateIndex', models.PositiveIntegerField()),
                ('holding', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equityBreakdowns', to='data.Holding')),
            ],
            options={
                'verbose_name': 'HoldingEquityBreakdown',
                'verbose_name_plural': 'HoldingEquityBreakdowns',
            },
        ),
        migrations.AlterField(
            model_name='userdisplayholding',
            name='holding',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='associated_holding', to='data.Holding'),
        ),
    ]
