# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-03 05:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0009_auto_20160801_2230'),
    ]

    operations = [
        migrations.AddField(
            model_name='investmentoption',
            name='threeYearReturn',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
