# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-11-23 15:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0010_auto_20161120_0009'),
    ]

    operations = [
        migrations.CreateModel(
            name='HoldingReturns',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('oneYearReturns', models.FloatField()),
                ('twoYearReturns', models.FloatField()),
                ('threeYearReturns', models.FloatField()),
                ('holding', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='returns', to='data.Holding')),
            ],
        ),
        migrations.AlterField(
            model_name='userdisplayholding',
            name='holding',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.Holding'),
        ),
    ]
