# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-03 16:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0011_auto_20160803_1408'),
    ]

    operations = [
        migrations.AlterField(
            model_name='yodleeaccount',
            name='isManual',
            field=models.BooleanField(default=False),
        ),
    ]
