# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-11-24 04:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0011_auto_20161123_1553'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userreturns',
            old_name='threeYearReturns',
            new_name='oneMonthReturns',
        ),
        migrations.RenameField(
            model_name='userreturns',
            old_name='twoYearReturns',
            new_name='threeMonthReturns',
        ),
        migrations.AddField(
            model_name='holdingreturns',
            name='oneMonthReturns',
            field=models.FloatField(default=0.0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='holdingreturns',
            name='threeMonthReturns',
            field=models.FloatField(default=0.0),
            preserve_default=False,
        ),
    ]
