# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-11-24 14:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0012_auto_20161124_0405'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='holdingreturns',
            options={'verbose_name': 'HoldingReturn', 'verbose_name_plural': 'HoldingReturns'},
        ),
    ]
