# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-08-05 04:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0012_auto_20160803_1606'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assetclassification',
            name='holding',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assetClassifications', to='data.Holding'),
        ),
        migrations.AlterField(
            model_name='balance',
            name='historicalBalance',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='balance', to='data.HistoricalBalance'),
        ),
        migrations.AlterField(
            model_name='historicalbalance',
            name='yodleeAccount',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historicalBalances', to='data.YodleeAccount'),
        ),
        migrations.AlterField(
            model_name='holding',
            name='yodleeAccount',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='holdings', to='data.YodleeAccount'),
        ),
        migrations.AlterField(
            model_name='investmentoption',
            name='yodleeAccount',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='investmentOptions', to='data.YodleeAccount'),
        ),
        migrations.AlterField(
            model_name='investmentplan',
            name='yodleeAccount',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='investmentPlan', to='data.YodleeAccount'),
        ),
        migrations.AlterField(
            model_name='yodleeaccount',
            name='userData',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='yodleeAccounts', to='data.UserData'),
        ),
    ]
