# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-06 01:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0013_auto_20160805_0459'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investmentoption',
            name='priceAsOfDate',
            field=models.DateField(blank=True, null=True),
        ),
    ]
