# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-12-18 22:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0014_transaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='memo',
            field=models.TextField(blank=True, null=True),
        ),
    ]
