# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-06 02:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0014_auto_20160806_0148'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricReturns',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oneMonthReturn', models.FloatField()),
                ('threeMonthReturn', models.FloatField()),
                ('oneYearReturn', models.FloatField()),
                ('threeYearReturn', models.FloatField()),
                ('fiveYearReturn', models.FloatField()),
                ('tenYearReturn', models.FloatField()),
            ],
        ),
        migrations.RemoveField(
            model_name='investmentoption',
            name='fiveYearReturn',
        ),
        migrations.RemoveField(
            model_name='investmentoption',
            name='oneMonthReturn',
        ),
        migrations.RemoveField(
            model_name='investmentoption',
            name='oneYearReturn',
        ),
        migrations.RemoveField(
            model_name='investmentoption',
            name='tenYearReturn',
        ),
        migrations.RemoveField(
            model_name='investmentoption',
            name='threeMonthReturn',
        ),
        migrations.RemoveField(
            model_name='investmentoption',
            name='threeYearReturn',
        ),
        migrations.AddField(
            model_name='historicreturns',
            name='investmentOption',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='historicReturns', to='data.InvestmentOption'),
        ),
    ]
