# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-06 21:15
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0015_auto_20160806_0253'),
    ]

    operations = [
        migrations.AddField(
            model_name='holding',
            name='createdAt',
            field=models.DateTimeField(default=datetime.datetime(2016, 8, 6, 21, 15, 0, 549298, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='yodleeaccount',
            name='lastHoldingsUpdate',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2016, 8, 6, 21, 15, 12, 286070, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
