# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-12-18 22:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0015_transaction_memo'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercurrentholding',
            name='quovoCusip',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='usercurrentholding',
            name='quovoSecname',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='usercurrentholding',
            name='quovoTicker',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='holding',
            name='secname',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
