# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-12-18 22:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0016_auto_20161218_2241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='holding',
            name='secname',
            field=models.CharField(blank=True, max_length=200, null=True, unique=True),
        ),
    ]
