# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-08 03:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0016_auto_20160806_2115'),
    ]

    operations = [
        migrations.CreateModel(
            name='SecurityPrice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('price', models.DecimalField(decimal_places=6, max_digits=11)),
            ],
        ),
        migrations.RenameModel(
            old_name='Stock',
            new_name='Security',
        ),
        migrations.RemoveField(
            model_name='stockprice',
            name='stock',
        ),
        migrations.DeleteModel(
            name='StockPrice',
        ),
        migrations.AddField(
            model_name='securityprice',
            name='stock',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='securityPrice', to='data.Security'),
        ),
    ]
