# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-12-18 22:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0017_auto_20161218_2243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='quovoID',
            field=models.IntegerField(unique=True),
        ),
    ]
