# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-08-10 04:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0017_auto_20160808_0308'),
    ]

    operations = [
        migrations.AddField(
            model_name='yodleeaccount',
            name='updatedAt',
            field=models.DateField(blank=True, null=True),
        ),
    ]
