# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-12-22 01:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0018_auto_20161218_2258'),
    ]

    operations = [
        migrations.CreateModel(
            name='AverageUserReturns',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('oneYearReturns', models.FloatField()),
                ('twoYearReturns', models.FloatField()),
                ('threeYearReturns', models.FloatField()),
                ('oneMonthReturns', models.FloatField()),
                ('threeMonthReturns', models.FloatField()),
            ],
            options={
                'verbose_name': 'AverageUserReturn',
                'verbose_name_plural': 'AverageUserReturns',
            },
        ),
        migrations.CreateModel(
            name='AverageUserSharpe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdAt', models.DateTimeField()),
            ],
        ),
        migrations.AddField(
            model_name='userdisplayholding',
            name='quovoCusip',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='userdisplayholding',
            name='quovoSecname',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='userdisplayholding',
            name='quovoTicker',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='userhistoricalholding',
            name='quovoCusip',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='userhistoricalholding',
            name='quovoSecname',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='userhistoricalholding',
            name='quovoTicker',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='userreturns',
            name='threeYearReturns',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userreturns',
            name='twoYearReturns',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
