# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-08-10 04:29
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0018_yodleeaccount_updatedat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='holding',
            name='currencyType',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='holding',
            name='optionType',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='holding',
            name='symbol',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='yodleeaccount',
            name='updatedAt',
            field=models.DateField(auto_now_add=True, default=datetime.datetime(2016, 8, 10, 4, 29, 49, 156558, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
