# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-08-10 04:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0019_auto_20160810_0429'),
    ]

    operations = [
        migrations.AlterField(
            model_name='yodleeaccount',
            name='updatedAt',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
