# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-12-23 20:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0020_usersharpe'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usercurrentholding',
            name='quovoSecname',
        ),
        migrations.RemoveField(
            model_name='userdisplayholding',
            name='quovoSecname',
        ),
        migrations.RemoveField(
            model_name='userhistoricalholding',
            name='quovoSecname',
        ),
    ]
