# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-08-10 04:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0020_auto_20160810_0430'),
    ]

    operations = [
        migrations.AlterField(
            model_name='holding',
            name='currencyType',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='holding',
            name='symbol',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
