# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-08-12 03:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0021_auto_20160810_0434'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='yodleeaccount',
            name='lastHoldingsUpdate',
        ),
        migrations.RemoveField(
            model_name='yodleeaccount',
            name='lastUpdated',
        ),
    ]
