# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-12-24 06:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0021_auto_20161223_2027'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='averageusersharpe',
            options={'verbose_name': 'AverageUserSharpe', 'verbose_name_plural': 'AverageUserSharpes'},
        ),
        migrations.AddField(
            model_name='averageuserreturns',
            name='ageGroup',
            field=models.PositiveSmallIntegerField(default=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='averageusersharpe',
            name='ageGroup',
            field=models.PositiveSmallIntegerField(default=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='averageusersharpe',
            name='mean',
            field=models.FloatField(default=0.5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='averageusersharpe',
            name='std',
            field=models.FloatField(default=0.25),
            preserve_default=False,
        ),
    ]
