# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-08-12 03:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0022_auto_20160812_0305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='holding',
            name='contractQuantity',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='holding',
            name='description',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='holding',
            name='quantity',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='holding',
            name='unvestedQuantity',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='holding',
            name='vestedQuantity',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
