# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-08-21 10:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0023_auto_20160812_0324'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='yodleeaccount',
            name='updatedAt',
        ),
    ]
