# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-12-27 08:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0024_auto_20161227_0740'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='memo',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
