# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-08-21 10:37
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0024_remove_yodleeaccount_updatedat'),
    ]

    operations = [
        migrations.AddField(
            model_name='yodleeaccount',
            name='updatedAt',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2016, 8, 21, 10, 37, 44, 640356, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
