# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-01-04 02:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0025_auto_20161227_0821'),
        ('data', '0025_auto_20161227_0820'),
    ]

    operations = [
    ]
