# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-08-22 05:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0025_yodleeaccount_updatedat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='yodleeaccount',
            name='updatedAt',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
