# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-01-04 02:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0026_merge'),
    ]

    operations = [
        migrations.CreateModel(
            name='HoldingJoin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('compositePercent', models.FloatField()),
            ],
            options={
                'verbose_name': 'HoldingJoin',
                'verbose_name_plural': 'HoldingJoins',
            },
        ),
        migrations.AddField(
            model_name='holding',
            name='isFundOfFunds',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='cusip',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='ticker',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='holdingjoin',
            name='childHolding',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parentJoiner', to='data.Holding'),
        ),
        migrations.AddField(
            model_name='holdingjoin',
            name='parentHolding',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='childJoiner', to='data.Holding'),
        ),
    ]
