# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-08-28 06:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0027_auto_20160828_0648'),
    ]

    operations = [
        migrations.AddField(
            model_name='holding',
            name='metaData',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='data.HoldingMetaData'),
        ),
    ]
