# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-01-09 21:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0028_holding_mstarid'),
    ]

    operations = [
        migrations.CreateModel(
            name='HoldingDividends',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('date', models.DateField()),
                ('value', models.FloatField()),
                ('holding', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dividends', to='data.Holding')),
            ],
            options={
                'verbose_name': 'HoldingDividend',
                'verbose_name_plural': 'HoldingDividends',
            },
        ),
    ]
