# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-01-12 01:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_quovouser_didlink'),
        ('data', '0030_treasurybondvalue'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brokerage_name', models.CharField(blank=True, max_length=100, null=True)),
                ('nickname', models.CharField(blank=True, max_length=100, null=True)),
                ('quovoID', models.IntegerField(unique=True)),
                ('active', models.BooleanField(default=True)),
                ('quovoUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userAccounts', to='dashboard.QuovoUser')),
            ],
            options={
                'verbose_name': 'Account',
                'verbose_name_plural': 'Accounts',
            },
        ),
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quovoID', models.IntegerField(unique=True)),
                ('description', models.CharField(blank=True, max_length=100, null=True)),
                ('is_taxable', models.BooleanField()),
                ('nickname', models.CharField(blank=True, max_length=100, null=True)),
                ('owner_type', models.CharField(blank=True, max_length=100, null=True)),
                ('portfolio_name', models.CharField(blank=True, max_length=100, null=True)),
                ('portfolio_type', models.CharField(blank=True, max_length=100, null=True)),
                ('active', models.BooleanField(default=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accounts', to='data.Account', to_field=b'quovoID')),
                ('quovoUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userPortfolios', to='dashboard.QuovoUser')),
            ],
            options={
                'verbose_name': 'Portfolio',
                'verbose_name_plural': 'Portfolios',
            },
        ),
        migrations.AddField(
            model_name='transaction',
            name='account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='accountTransaction', to='data.Account', to_field=b'quovoID'),
        ),
        migrations.AddField(
            model_name='usercurrentholding',
            name='account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='accountCurrentHoldings', to='data.Account', to_field=b'quovoID'),
        ),
        migrations.AddField(
            model_name='usercurrentholding',
            name='portfolio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='portfolioCurrentHoldings', to='data.Portfolio', to_field=b'quovoID'),
        ),
        migrations.AddField(
            model_name='userdisplayholding',
            name='account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='accountDisplayHoldings', to='data.Account', to_field=b'quovoID'),
        ),
        migrations.AddField(
            model_name='userdisplayholding',
            name='portfolio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='portfolioDisplayHoldings', to='data.Portfolio', to_field=b'quovoID'),
        ),
        migrations.AddField(
            model_name='userhistoricalholding',
            name='account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='accountHistoricalHoldings', to='data.Account', to_field=b'quovoID'),
        ),
        migrations.AddField(
            model_name='userhistoricalholding',
            name='portfolio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='portfolioHistoricalHoldings', to='data.Portfolio', to_field=b'quovoID'),
        ),
    ]
