# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-08-31 13:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0030_auto_20160831_1302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='holding',
            name='metaData',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='data.HoldingMetaData'),
        ),
    ]
