# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-01-26 02:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0011_quovouser_didlink'),
        ('data', '0031_auto_20170112_0159'),
    ]

    operations = [
        migrations.CreateModel(
            name='AverageUserBondEquity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('ageGroup', models.PositiveSmallIntegerField()),
                ('bond', models.FloatField()),
                ('equity', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='UserBondEquity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('bond', models.FloatField()),
                ('equity', models.FloatField()),
                ('quovoUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userBondEquity', to='dashboard.QuovoUser')),
            ],
        ),
    ]
