# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-02 05:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0032_auto_20160902_0502'),
    ]

    operations = [
        migrations.AddField(
            model_name='yodleeaccount',
            name='requiresProcessing',
            field=models.BooleanField(default=False),
        ),
    ]
