# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-01-27 18:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0032_averageuserbondequity_userbondequity'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='averageuserbondequity',
            options={'verbose_name': 'AverageUserBondEquity', 'verbose_name_plural': 'AverageUserBondEquities'},
        ),
        migrations.AlterField(
            model_name='transaction',
            name='memo',
            field=models.TextField(blank=True, null=True),
        ),
    ]
