# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-01-26 02:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0032_averageuserbondequity_userbondequity'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='averageuserbondequity',
            options={'verbose_name': 'AverageUserBondEquity', 'verbose_name_plural': 'AverageUserBondEquities'},
        ),
    ]
