# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-01-29 19:26
from __future__ import unicode_literals

from django.db import migrations, models

MUTUAL_FUND = "MUTF"
CASH = "CASH"
STOCK = "STOC"  # Also stands for Equity
FUND_OF_FUNDS = "FOFF"
IGNORE = "IGNO"  # Also stands for unidentifiable.

CATEGORY_CHOICES = (
    (MUTUAL_FUND, "Mutual Fund"),
    (CASH, "Cash"),
    (STOCK, "Stock"),
    (FUND_OF_FUNDS, "Fund of Funds"),
    (IGNORE, "Should Ignore")
)

def identify_category(apps, schema_editor):
    Holding = apps.get_model('data', 'Holding')
    for hold in Holding.objects.all():
        if hasattr(hold, "isNAVValued") and hasattr(hold, "shouldIgnore") and hasattr(hold, "isFundOfFunds"):
            if hold.isNAVValued:
                hold.category = "MUTF"
            elif hold.isFundOfFunds:
                hold.category = "FOFF"
            elif hold.shouldIgnore:
                hold.category = "IGNO"
            else:
                hold.category = "STOC"
            hold.save()

class Migration(migrations.Migration):

    dependencies = [
        ('data', '0033_auto_20170127_1803'),
    ]

    operations = [
        migrations.AddField(
            model_name='holding',
            name='category',
            field=models.CharField(
                max_length=4,
                choices=CATEGORY_CHOICES,
                default="IGNO"
            )
        ),
        migrations.RunPython(identify_category),
        migrations.RemoveField(
            model_name='holding',
            name='isNAVValued'
        ),
        migrations.RemoveField(
            model_name='holding',
            name='shouldIgnore'
        ),
        migrations.RemoveField(
            model_name='holding',
            name='isFundOfFunds'
        )
    ]
