# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-02-02 21:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0033_auto_20170127_1803'),
    ]

    operations = [
        migrations.CreateModel(
            name='AverageFees',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('avgFees', models.FloatField()),
            ],
            options={
                'verbose_name': 'AverageUserFees',
                'verbose_name_plural': 'AverageUserFees',
            },
        ),
    ]
