# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-02-02 21:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0034_averagefees'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AverageFees',
            new_name='AverageUserFee',
        ),
    ]
