# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-02-08 19:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0035_auto_20170202_2112'),
        ('data', '0035_auto_20170204_2240'),
    ]

    operations = [
    ]
