# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-02-08 19:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0036_merge'),
    ]

    operations = [
        migrations.AddField(
            model_name='holding',
            name='securityType',
            field=models.CharField(blank=True, max_length=20, null=True),
        )
    ]
