# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-02-08 18:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0036_merge'),
    ]

    operations = [
        migrations.AddField(
            model_name='holding',
            name='isFundOfFunds',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='holding',
            name='isNAVValued',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='holding',
            name='securityType',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='holding',
            name='shouldIgnore',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='usercurrentholding',
            name='holding',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='currentHoldingChild', to='data.Holding'),
        ),
        migrations.AlterField(
            model_name='userdisplayholding',
            name='holding',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='displayHoldingChild', to='data.Holding'),
        ),
    ]
