# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-02-11 19:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0037_auto_20170208_1937'),
        ('data', '0037_auto_20170208_1840'),
    ]

    operations = [
    ]
