# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-02-12 17:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0038_merge'),
    ]

    operations = [

    ]
