# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-02-18 22:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0040_remove_holding_securitytype'),
    ]

    operations = [
        migrations.AddField(
            model_name='userreturns',
            name='yearToDate',
            field=models.FloatField(default=0.0),
            preserve_default=False,
        ),
    ]
