# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-02-19 19:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0041_userreturns_yeartodate'),
    ]

    operations = [
        migrations.AddField(
            model_name='holdingreturns',
            name='yearToDate',
            field=models.FloatField(default=0.0),
            preserve_default=False,
        ),
    ]
