# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-02-19 22:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0042_holdingreturns_yeartodate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercurrentholding',
            name='holding',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='currentHoldingChild', to='data.Holding'),
        ),
        migrations.AlterField(
            model_name='userdisplayholding',
            name='holding',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='displayHoldingChild', to='data.Holding'),
        ),
    ]
