# -*- coding: utf-8 -*-
# Generated by Django 1.11a1 on 2017-02-22 01:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0043_auto_20170219_2205'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='treasurybondvalue',
            options={'verbose_name': 'TreasuryBondValue', 'verbose_name_plural': 'TreasuryBondValues'},
        ),
        migrations.AddField(
            model_name='averageuserreturns',
            name='yearToDate',
            field=models.FloatField(default=0.0),
            preserve_default=False,
        ),
    ]
