# -*- coding: utf-8 -*-
# Generated by Django 1.11a1 on 2017-02-22 17:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0044_auto_20170222_0146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='ticker_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
