# -*- coding: utf-8 -*-
# Generated by Django 1.11a1 on 2017-02-25 20:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0045_auto_20170222_1755'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portfolios', to='data.Account', to_field=b'quovoID'),
        ),
    ]
