# -*- coding: utf-8 -*-
# Generated by Django 1.11a1 on 2017-02-26 19:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0045_auto_20170222_1755'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountReturns',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('yearToDate', models.FloatField()),
                ('oneYearReturns', models.FloatField()),
                ('twoYearReturns', models.FloatField()),
                ('threeYearReturns', models.FloatField()),
                ('oneMonthReturns', models.FloatField()),
                ('threeMonthReturns', models.FloatField()),
                ('quovoID', models.IntegerField()),
                ('account', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='accountReturns', to='data.Account')),
            ],
            options={
                'verbose_name': 'AccountReturn',
                'verbose_name_plural': 'AccountReturns',
            },
        ),
        migrations.RemoveField(
            model_name='userreturns',
            name='quovoUser',
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portfolios', to='data.Account', to_field=b'quovoID'),
        ),
        migrations.DeleteModel(
            name='UserReturns',
        ),
    ]
