# -*- coding: utf-8 -*-
# Generated by Django 1.11a1 on 2017-02-26 19:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0046_auto_20170226_1912'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accountreturns',
            name='quovoID',
        ),
    ]
