# -*- coding: utf-8 -*-
# Generated by Django 1.11a1 on 2017-03-01 17:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0046_auto_20170225_2053'),
        ('data', '0047_remove_accountreturns_quovoid'),
    ]

    operations = [
    ]
