# -*- coding: utf-8 -*-
# Generated by Django 1.11a1 on 2017-03-01 21:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion

from dashboard.models import QuovoUser


def create_fees(apps, schema_editor):
    for qUser in QuovoUser.objects.all():
        qUser.updateFees()

class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0021_auto_20170301_1754'),
        ('data', '0049_fees'),
    ]

    operations = [
        migrations.RunPython(create_fees)
    ]
