# -*- coding: utf-8 -*-
# Generated by Django 1.11a1 on 2017-03-10 18:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0053_data_migration_benchmark'),
    ]

    operations = [
        migrations.RenameField('UserTracking', 'createdAt', 'created_at'),
    ]
