# -*- coding: utf-8 -*-
# Generated by Django 1.11a1 on 2017-05-15 17:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0052_auto_20170515_1721'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='quovo_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_accounts', to='dashboard.QuovoUser'),
        ),
        migrations.AlterField(
            model_name='accountreturns',
            name='account',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='account_returns', to='data.Account'),
        ),
        migrations.AlterField(
            model_name='holdingassetbreakdown',
            name='holding',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asset_breakdown', to='data.Holding'),
        ),
        migrations.AlterField(
            model_name='holdingbondbreakdown',
            name='holding',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bond_breakdown', to='data.Holding'),
        ),
        migrations.AlterField(
            model_name='holdingequitybreakdown',
            name='holding',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equity_breakdown', to='data.Holding'),
        ),
        migrations.AlterField(
            model_name='holdingexpenseratio',
            name='holding',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expense_ratios', to='data.Holding'),
        ),
        migrations.AlterField(
            model_name='holdingjoin',
            name='child_holding',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parent_joiner', to='data.Holding'),
        ),
        migrations.AlterField(
            model_name='holdingjoin',
            name='parent_holding',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='child_joiner', to='data.Holding'),
        ),
        migrations.AlterField(
            model_name='holdingprice',
            name='holding',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='holding_prices', to='data.Holding'),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='quovo_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_portfolios', to='dashboard.QuovoUser'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='account_transaction', to='data.Account', to_field=b'quovo_id'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='quovo_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_transaction', to='dashboard.QuovoUser'),
        ),
        migrations.AlterField(
            model_name='userbondequity',
            name='quovo_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_bond_equity', to='dashboard.QuovoUser'),
        ),
        migrations.AlterField(
            model_name='usercurrentholding',
            name='account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='account_current_holdings', to='data.Account', to_field=b'quovo_id'),
        ),
        migrations.AlterField(
            model_name='usercurrentholding',
            name='holding',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='current_holding_child', to='data.Holding'),
        ),
        migrations.AlterField(
            model_name='usercurrentholding',
            name='portfolio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='portfolio_current_holdings', to='data.Portfolio', to_field=b'quovo_id'),
        ),
        migrations.AlterField(
            model_name='usercurrentholding',
            name='quovo_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_current_holdings', to='dashboard.QuovoUser'),
        ),
        migrations.AlterField(
            model_name='userdisplayholding',
            name='account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='account_display_holdings', to='data.Account', to_field=b'quovo_id'),
        ),
        migrations.AlterField(
            model_name='userdisplayholding',
            name='holding',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='display_holding_child', to='data.Holding'),
        ),
        migrations.AlterField(
            model_name='userdisplayholding',
            name='portfolio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='portfolio_display_holdings', to='data.Portfolio', to_field=b'quovo_id'),
        ),
        migrations.AlterField(
            model_name='userdisplayholding',
            name='quovo_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_display_holdings', to='dashboard.QuovoUser'),
        ),
        migrations.AlterField(
            model_name='userhistoricalholding',
            name='account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='account_historical_holdings', to='data.Account', to_field=b'quovo_id'),
        ),
        migrations.AlterField(
            model_name='userhistoricalholding',
            name='portfolio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='portfolio_historical_holdings', to='data.Portfolio', to_field=b'quovo_id'),
        ),
        migrations.AlterField(
            model_name='userhistoricalholding',
            name='quovo_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_historical_holdings', to='dashboard.QuovoUser'),
        ),
        migrations.AlterField(
            model_name='usersharpe',
            name='quovo_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_sharpes', to='dashboard.QuovoUser'),
        ),
    ]
