# -*- coding: utf-8 -*-
# Generated by Django 1.11a1 on 2017-06-07 19:43
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('category', models.CharField(choices=[('Risk', 'Risk'), ('Return', 'Return'), ('Asset', 'Asset'), ('Cost', 'Cost'), ('Other', 'Other')], max_length=50)),
                ('endpoint', models.CharField(max_length=50)),
                ('module_id', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Module',
                'verbose_name_plural': 'Modules',
            },
        ),
        migrations.CreateModel(
            name='ProgressTracker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('did_link', models.BooleanField(default=False)),
                ('complete_identification', models.BooleanField(default=False)),
                ('did_open_dashboard', models.BooleanField(default=False)),
                ('dashboard_data_shown', models.BooleanField(default=False)),
                ('annotation_view_count', models.IntegerField(default=0)),
                ('hover_module_count', models.IntegerField(default=0)),
                ('total_dashboard_view_time', models.FloatField(default=0)),
                ('total_filters', models.IntegerField(default=0)),
                ('tutorial_time', models.IntegerField(default=0)),
                ('last_dashboard_view', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'ProgressTracker',
                'verbose_name_plural': 'ProgressTrackers',
            },
        ),
        migrations.CreateModel(
            name='ProgressTrackerModuleView',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module_name', models.CharField(max_length=100)),
                ('views', models.IntegerField(default=0)),
                ('tracker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='moduleViews', to='dashboard.ProgressTracker')),
            ],
            options={
                'verbose_name': 'ProgressTrackerModuleView',
                'verbose_name_plural': 'ProgressTrackerModuleViews',
            },
        ),
        migrations.CreateModel(
            name='QuovoUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quovo_id', models.IntegerField()),
                ('is_completed', models.BooleanField(default=False)),
                ('current_historical_index', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'QuovoUser',
                'verbose_name_plural': 'QuovoUsers',
            },
        ),
        migrations.CreateModel(
            name='RecoveryLink',
            fields=[
                ('id', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('link', models.CharField(max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recovery_links', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'RecoveryLink',
                'verbose_name_plural': 'RecoveryLinks',
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('birthday', models.DateField()),
                ('created_at', models.DateField(auto_now_add=True)),
                ('company', models.CharField(blank=True, max_length=50, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'UserProfile',
                'verbose_name_plural': 'UserProfiles',
            },
        ),
        migrations.CreateModel(
            name='UserTracking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(default=0)),
                ('created_at', models.DateField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'UserTracking',
                'verbose_name_plural': 'UserTrackings',
            },
        ),
        migrations.AddField(
            model_name='quovouser',
            name='user_profile',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='quovo_user', to='dashboard.UserProfile'),
        ),
        migrations.AddField(
            model_name='progresstracker',
            name='profile',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='progress', to='dashboard.UserProfile'),
        ),
    ]
