# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-10-08 21:59
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('category', models.CharField(choices=[('Risk', 'Risk'), ('Return', 'Return'), ('Asset', 'Asset'), ('Cost', 'Cost')], max_length=50)),
                ('endpoint', models.CharField(max_length=50)),
                ('moduleID', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Module',
                'verbose_name_plural': 'Modules',
            },
        ),
        migrations.CreateModel(
            name='QuovoUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quovoID', models.IntegerField()),
                ('isCompleted', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'QuovoUser',
                'verbose_name_plural': 'QuovoUsers',
            },
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='email',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='company',
            field=models.CharField(default='test', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userprofile',
            name='zipCode',
            field=models.CharField(default=123, max_length=5),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='quovouser',
            name='userProfile',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='dashboard.UserProfile'),
        ),
    ]
