# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-10-09 18:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_quovouser_currenthistoricalindex'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quovouser',
            name='userProfile',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='quovoUser', to='dashboard.UserProfile'),
        ),
    ]
