# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-11-10 19:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_auto_20161009_1846'),
    ]

    operations = [
        migrations.AddField(
            model_name='quovouser',
            name='hasNotification',
            field=models.BooleanField(default=False),
        ),
    ]
