# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-11-10 19:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_quovouser_hasnotification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quovouser',
            name='hasNotification',
        ),
    ]
