# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-11-24 14:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_remove_quovouser_hasnotification'),
    ]

    operations = [
        migrations.AddField(
            model_name='quovouser',
            name='didLink',
            field=models.BooleanField(default=False),
        ),
    ]
