# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-01-12 01:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0031_auto_20170112_0159'),
        ('dashboard', '0007_quovouser_didlink'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountFilter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.Account')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accountFilters', to='dashboard.UserProfile')),
            ],
            options={
                'verbose_name': 'AccountFilter',
                'verbose_name_plural': 'AccountFilters',
            },
        ),
    ]
