# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-01-12 02:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_accountfilter'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accountfilter',
            name='account',
        ),
        migrations.RemoveField(
            model_name='accountfilter',
            name='profile',
        ),
        migrations.DeleteModel(
            name='AccountFilter',
        ),
    ]
