# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-01-13 00:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_auto_20170112_0221'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quovouser',
            name='didLink',
        ),
    ]
