# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-01-14 00:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0010_remove_quovouser_didlink'),
    ]

    operations = [
        migrations.AddField(
            model_name='quovouser',
            name='didLink',
            field=models.BooleanField(default=False),
        ),
    ]
