# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-02-11 17:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0011_quovouser_didlink'),
    ]

    operations = [
        migrations.AlterField(
            model_name='module',
            name='category',
            field=models.CharField(choices=[('Risk', 'Risk'), ('Return', 'Return'), ('Asset', 'Asset'), ('Cost', 'Cost'), ('Other', 'Other')], max_length=50),
        ),
    ]
