# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-02-18 19:31
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dashboard', '0014_auto_20170218_1828'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecoveryLink',
            fields=[
                ('id', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('link', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recoveryLinks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'RecoveryLink',
                'verbose_name_plural': 'RecoveryLinks',
            },
        ),
    ]
