# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-02-18 21:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0015_recoverylink'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recoverylink',
            name='is_active',
        ),
    ]
