# -*- coding: utf-8 -*-
# Generated by Django 1.11a1 on 2017-02-25 20:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0016_remove_recoverylink_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgressTracker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('did_link', models.BooleanField(default=False)),
                ('complete_identification', models.BooleanField(default=False)),
                ('dashboard_data_shown', models.BooleanField(default=False)),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='progress', to='dashboard.UserProfile')),
            ],
        ),
    ]
