# -*- coding: utf-8 -*-
# Generated by Django 1.11a1 on 2017-02-25 22:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0018_auto_20170225_2144'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgressTrackerModuleView',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module_name', models.CharField(max_length=100)),
                ('views', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'ProgressTrackerModuleView',
                'verbose_name_plural': 'ProgressTrackerModuleViews',
            },
        ),
        migrations.AlterModelOptions(
            name='progresstracker',
            options={'verbose_name': 'ProgressTracker', 'verbose_name_plural': 'ProgressTrackers'},
        ),
        migrations.RenameField(
            model_name='progresstracker',
            old_name='did_hover_module',
            new_name='hover_module_count',
        ),
        migrations.AddField(
            model_name='progresstrackermoduleview',
            name='tracker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='moduleViews', to='dashboard.ProgressTracker'),
        ),
    ]
