# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-02-18 21:35
from __future__ import unicode_literals
from django.db import migrations
from dashboard.models import UserProfile, ProgressTracker


def create_progress_tracker(apps, schema_editor):
    profiles = UserProfile.objects.all()
    for p in profiles:
        ProgressTracker.objects.create(profile=p)

class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0021_auto_20170301_1754'),
    ]

    operations = [
        migrations.RunPython(create_progress_tracker)
    ]
