# -*- coding: utf-8 -*-
# Generated by Django 1.11a1 on 2017-03-01 17:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0020_create_progress_tracker'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='state',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='expectedRetirementAge',
            field=models.IntegerField(default=60),
        ),
    ]
