# -*- coding: utf-8 -*-
# Generated by Django 1.11a1 on 2017-03-10 18:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0021_auto_20170301_1754'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='expectedRetirementAge',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='firstName',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='lastName',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='zipCode',
        ),
    ]
