# -*- coding: utf-8 -*-
# Generated by Django 1.11a1 on 2017-03-10 18:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0023_usertracking'),
    ]

    operations = [
        migrations.AddField(
            model_name='progresstracker',
            name='last_dashboard_view',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
