# -*- coding: utf-8 -*-
# Generated by Django 1.11a1 on 2017-03-10 18:46
from __future__ import unicode_literals

from django.db import migrations, models

from dashboard.models import Module


def modulemod(apps, schema_editor):
    m1 = Module.objects.filter(name='Returns').first()
    m2 = Module.objects.filter(name='Returns Comparison').first()
    if m1:
        m1.name = 'Backtested Returns'
        m1.save()
    if m2:
        m2.name = 'Backtested Returns Comparison'
        m2.save()

class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0024_progresstracker_last_dashboard_view'),
    ]

    operations = [
        migrations.RunPython(modulemod)
    ]
