# -*- coding: utf-8 -*-
# Generated by Django 1.11a1 on 2017-03-10 18:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0025_modulemod'),
    ]

    operations = [
        migrations.RenameField('UserTracking', 'createdAt', 'created_at'),
        migrations.RenameField('QuovoUser', 'quovoID', 'quovo_id'),
        migrations.RenameField('QuovoUser', 'isCompleted', 'is_completed'),
        migrations.RenameField('QuovoUser', 'userProfile', 'user_profile'),
        migrations.RenameField('QuovoUser', 'currentHistoricalIndex', 'current_historical_index'),
        migrations.RenameField('UserProfile', 'createdAt', 'created_at'),
    ]
