# -*- coding: utf-8 -*-
# Generated by Django 1.11a1 on 2017-05-15 17:36
from __future__ import unicode_literals

import django
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0025_modulemod'),
    ]

    operations = [
        migrations.RenameField(
            model_name='module',
            old_name='moduleID',
            new_name='module_id',
        ),
        migrations.RenameField(
            model_name='quovouser',
            old_name='userProfile',
            new_name='user_profile',
        ),
        migrations.RenameField(
            model_name='quovouser',
            old_name='currentHistoricalIndex',
            new_name='current_historical_index',
        ),
        migrations.RenameField(
            model_name='quovouser',
            old_name='isCompleted',
            new_name='is_completed',
        ),
        migrations.RenameField(
            model_name='quovouser',
            old_name='quovoID',
            new_name='quovo_id',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='createdAt',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='usertracking',
            old_name='createdAt',
            new_name='created_at',
        ),
    ]
