# -*- coding: utf-8 -*-
# Generated by Django 1.11a1 on 2017-05-15 17:36
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0026_auto_20170515_1736'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recoverylink',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recovery_links', to=settings.AUTH_USER_MODEL),
        ),
    ]
