# -*- coding: utf-8 -*-
# Generated by Django 1.11a1 on 2017-05-15 18:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0027_auto_20170515_1736'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quovouser',
            name='user_profile',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='quovo_user', to='dashboard.UserProfile'),
        ),
    ]
