# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-10-08 21:59
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HumanResourceProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=100)),
                ('zipCode', models.CharField(max_length=5)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'HumanResourceProfile',
                'verbose_name_plural': 'HumanResourceProfiles',
            },
        ),
        migrations.CreateModel(
            name='SetUpUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('company', models.CharField(max_length=100)),
                ('magic_link', models.CharField(max_length=100)),
                ('zipCode', models.CharField(max_length=5)),
            ],
            options={
                'verbose_name': 'SetUpUser',
                'verbose_name_plural': 'SetUpUsers',
            },
        ),
    ]
