# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-10-09 17:22
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('humanResources', '0003_auto_20161009_1708'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='setupuser',
            name='zipCode',
        ),
        migrations.AlterField(
            model_name='humanresourceprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='humanResourceProfile', to=settings.AUTH_USER_MODEL),
        ),
    ]
