# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-11-25 19:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('humanResources', '0005_auto_20161124_0633'),
    ]

    operations = [
        migrations.AddField(
            model_name='humanresourceprofile',
            name='employee_estimate',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='setupuser',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='setupuser',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
