# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-12-19 22:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('humanResources', '0006_auto_20161125_1917'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setupuser',
            name='id',
            field=models.CharField(max_length=32, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='setupuser',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
