# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-12-21 17:07
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('humanResources', '0007_auto_20161219_2228'),
    ]

    operations = [
        migrations.AddField(
            model_name='humanresourceprofile',
            name='subscription_date',
            field=models.DateField(auto_now_add=True, default=datetime.datetime(2016, 12, 21, 17, 7, 6, 351825, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
