# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-01-04 02:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('humanResources', '0008_humanresourceprofile_subscription_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='humanresourceprofile',
            name='employee_estimate',
        ),
    ]
