# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-01-17 00:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('humanResources', '0010_auto_20170114_2258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='humanresourceprofile',
            name='subscription_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
